# /web/docker-compose.yml

version: "3.9"

services:
  reverse-proxy:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - reverse_proxy_net

networks:
  reverse_proxy_net:
